### ISSUE TITLE
setting up c env

### ISSUE THREAD

**Issue by basfora** [cornellmotionstudio/JacksonDronev2#4]
move[ this section](https://github.com/cornellmotionstudio/JacksonDronev2/wiki/Radio-Control-&-Connections#program-radiomaster-to-control-drone) to separate page, update new method

add [checking connection with blink code](https://vanhunteradams.com/Pico/Setup/PicoSetup.html#Programming-the-Pico)

**Comment by JisooKim2336** [comment]
I have created a new page on setting up C environment(Nilkolai's way.)

[link](https://github.com/cornellmotionstudio/JacksonDronev2/wiki/Setting-C-Environment-for-Pico-Programming)
