### ISSUE TITLE
Pico setup

### ISSUE THREAD

**Issue by basfora** [cornellmotionstudio/JacksonDronev2#5]
Please separate the instructions and troubleshooting at this page > https://github.com/cornellmotionstudio/JacksonDronev2/wiki/Setting-C-Environment-for-Pico-Programming

Also, chapter 4 of what? Be specific when possible (:

**Comment by JisooKim2336** [comment]
Separated the instruction and troubleshooting. Also, specified which Chapter 4 it refers to.

**Comment by basfora** [comment]
On the trade off between providing to the students too much information or too little, this is leaning towards the latter. Please edit the page to look more like the previous instructions (with steps), since this is one of the project's main roadblocks for people that never used raspberry pi

**Comment by basfora** [comment]
On the trade off between providing to the students too much information or too little, this is leaning towards the latter. Please edit the page to look more like the previous instructions (with steps), since this is one of the main roadblocks in the project for people who never used raspberry pi

**Comment by JisooKim2336** [comment]
I've added multiple steps with sufficient detail. Please let me know if this is a good amount of details. If I need more, I will add them!

**Comment by basfora** [comment]
I'm closing this issue! Good job
